### ISSUE TITLE
another mixer

### ISSUE THREAD

**Issue by gentabiloso** [teran-mckinney/privcoin-python#1]
thanks for your work but any chance you'll make another version for bitmix.biz?
https://bitcointalk.org/index.php?topic=2099519.0

**privcoin wasn't active on bitcointalk since november, i think it's not secure anymore.**

**Comment by teran-mckinney** [comment]
Believe it or not, already in progress.

I've heard from privcoin over email before and they seem fine. I think ideally you would use two mixers in series, which is my next project.

**Comment by teran-mckinney** [comment]
I haven't tested it yet, could you give it a try?

https://github.com/teran-mckinney/bitmix-python

**Comment by gentabiloso** [comment]
it seems to work thanks
